name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *" # Tumakbo tuwing hatinggabi UTC (Araw-araw)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          # REQUIRED: Palitan mo ng TAMA mong username. (Modern-Cipher dapat)
          github_user_name: Modern-Cipher
          
          # Gumamit ng GITHUB_TOKEN para sa tamang permissions
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Output settings: DITO GINAGAWA ANG SNAKE IMAGE
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
            
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Ito ang branch na pinupuntahan ng image
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}